const { Router } = require('express');

const authRoutes = require('./auth.routes');
const eventosRoutes = require('./eventos.routes');
const pasajerosRoutes = require('./pasajeros.routes');
const adminRoutes = require('./admin.routes');
const adminUsuarioEmpresaRoutes = require('./admin.usuarioEmpresa.routes');
const empresaRoutes = require('./empresa.routes');
const convenioRoutes = require('./convenio.routes');
const kpiRoutes = require('./kpi.routes');
const araucanaRoutes = require('./araucana.routes');
const apiConsultaRoutes = require('./apiConsulta.routes');
const estudiantesRoutes = require('./estudiantes.routes');
const adultosMayoresRoutes = require('./adultosMayores.routes');
const pasajerosFrecuentesRoutes = require('./pasajerosFrecuentes.routes');
const integracionBeneficiariosRoutes = require('./integracionBeneficiarios.routes');
const carabinerosRoutes = require('./carabineros.routes');
const fachRoutes = require('./fach.routes');
const rolesRoutes = require('./roles.routes');
const apiRegistroRoutes = require('./apiRegistro.routes');
const beneficiarioRoutes = require('./beneficiario.routes');
const losAndesRoutes = require('./losAndes.routes');
const exportRoutes = require('./export.routes');
const registroTablaClienteCorporativoRoutes = require('./registroTablaClienteCorporativo.routes');
const clienteCorporativoTablaEmpresaRoutes = require('./clienteCorporativoTablaEmpresa.routes');
// const categoriaRoutes = require('./categoria.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/eventos', eventosRoutes);
router.use('/pasajeros', pasajerosRoutes);
router.use('/admin', adminRoutes);
router.use('/admin', adminUsuarioEmpresaRoutes);
router.use('/empresas', empresaRoutes);
router.use('/convenios', convenioRoutes);
router.use('/kpis', kpiRoutes);
router.use('/integraciones/beneficiarios', integracionBeneficiariosRoutes);
router.use('/integraciones', araucanaRoutes);
router.use('/integraciones', losAndesRoutes);
router.use('/apis-consulta', apiConsultaRoutes);
router.use('/apis-registro', apiRegistroRoutes);
router.use('/beneficiarios', beneficiarioRoutes);
router.use('/adultos-mayores', adultosMayoresRoutes);
router.use('/estudiantes', estudiantesRoutes);
router.use('/pasajeros-frecuentes', pasajerosFrecuentesRoutes);
router.use('/carabineros', carabinerosRoutes);
router.use('/fach', fachRoutes);
router.use('/roles', rolesRoutes);
router.use('/export', exportRoutes);
router.use('/tablas-clientes-corporativos', registroTablaClienteCorporativoRoutes);
router.use('/tablas-clientes-corporativos', clienteCorporativoTablaEmpresaRoutes);
// router.use('/categorias', categoriaRoutes);

module.exports = router;
